# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  aminimaneshweb:
    image: aminimaneshweb
    build:
      context: .
      dockerfile: Aminimanesh.Web/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 50014:50014
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
