version: '3.8'

services:
  aminimaneshweb:
    image: aminimaneshweb
    build:
      context: .
      dockerfile: Aminimanesh.Web/Dockerfile
    ports:
      - "50014:8080"
    environment:
      - MSSQL_SA_PASSWORD=@Googooli1381
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__AminimaneshConnection=Server=aminimaneshdb,1433;Initial Catalog=AminimaneshDb;Persist Security Info=False;User ID=sa;Password=@Googooli1381;MultipleActiveResultSets=False;Encrypt=no;TrustServerCertificate=True;Connection Timeout=30;
    depends_on:
      aminimaneshdb:
        condition: service_healthy

  aminimaneshdb:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: aminimaneshdb
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "@Googooli1381"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P @Googooli1381 -N -C -Q 'SELECT 1' || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:


networks:
  default:
    name: aminimanesh-network
    driver: bridge
